<?php
		include('helper/db_conn.php');
	
		if((isset($_REQUEST['pro_wc_id']))&&(isset($_REQUEST['prom_wc_id']))&&(isset($_REQUEST['pro_total_price']))&&(isset($_REQUEST['action']))&&($_REQUEST['action']=='update_variation'))
		{
			$pro_wc_id = $_REQUEST['pro_wc_id'];
			$prom_wc_id = $_REQUEST['prom_wc_id'];
			$pro_total_price = $_REQUEST['pro_total_price'];
			
			// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
			$ch = curl_init();

			
			curl_setopt($ch,CURLOPT_URL,'https://jewelbox.co.in/demo/wp-json/wc/v3/products/'.$prom_wc_id.'/variations/'.$pro_wc_id.'?consumer_key=ck_f328a742d3186568a5ea7926af691ee5842fda70&consumer_secret=cs_3902e2b339b57ddc680818e2d12338c9970e1aa2');
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
            //curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"regular_price\": \"24.54\",\n\"sales_price\":\"26.5\"\n}");
			curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n \"regular_price\": \"".$pro_total_price."\",\n\"sale_price\": \"".$pro_total_price."\"\n}");
			
			//curl_setopt($ch, CURLOPT_USERPWD, 'consumer_key' . ':' . 'consumer_secret');

			$headers = array();
			$headers[] = 'Content-Type: application/json';
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

			$result = curl_exec($ch);
			if (curl_errno($ch)) {
				// echo 'Error:' . curl_error($ch);
			}
			curl_close($ch);
			
			echo "1";
		}
		else if((isset($_REQUEST['prom_wc_id']))&&(isset($_REQUEST['action']))&&($_REQUEST['action']=='import_variation'))	
		{
			//echo "1";
			
			
		
			
			$prom_wc_id = $_REQUEST['prom_wc_id'];
			$prom_id = $_REQUEST['prom_id'];
			
			  $curl_handle=curl_init();
			  curl_setopt($curl_handle,CURLOPT_URL,'https://jewelbox.co.in/demo/wp-json/wc/v3/products/'.$prom_wc_id.'/variations?consumer_key=ck_f328a742d3186568a5ea7926af691ee5842fda70&consumer_secret=cs_3902e2b339b57ddc680818e2d12338c9970e1aa2');
			  //curl_setopt($curl_handle,CURLOPT_URL,'https://jewelbox.co.in/demo/wp-json/wc/v3/products?consumer_key=ck_f328a742d3186568a5ea7926af691ee5842fda70&consumer_secret=cs_3902e2b339b57ddc680818e2d12338c9970e1aa2');
			  curl_setopt($curl_handle,CURLOPT_CONNECTTIMEOUT,2);
			  curl_setopt($curl_handle,CURLOPT_RETURNTRANSFER,1);
			  $buffer = curl_exec($curl_handle);
			  curl_close($curl_handle);
			  if (empty($buffer)){
				  print "Nothing returned from url.<p>";
			  }
			  else{
				  /*
				  echo '<pre>';
				  var_dump(json_decode($buffer,true));
				  echo '</pre>';
				  //print $buffer;
				  */
				  
			  }
			  
			  //exit();
			  
			  $arrProduct = json_decode($buffer,true);
			 
			  for($iRow=0;$iRow<=count($arrProduct)-1;$iRow++)
			  {
				 
				  
				   $str = "
					select  * 
					 from  product
					where  pro_sku='".$arrProduct[$iRow]['sku']."'";
						 
					$dtTmp1 = getDatatable($str);
					
					$pro_name = '';
					$strRingSize = '';
					$strPurity = '';
					$strColor = '';
					$strComma = '';
					$arrAttributes = $arrProduct[$iRow]['attributes'];
					for($iRowAtt=0;$iRowAtt<=count($arrAttributes)-1;$iRowAtt++)
					{
						$pro_name .= $strComma.$arrAttributes[$iRowAtt]['name'].' - '.$arrAttributes[$iRowAtt]['option'];
						$strComma = ', ';
						
						if($arrAttributes[$iRowAtt]['name']=='Ring Size')
						{
							$strRingSize = $arrAttributes[$iRowAtt]['option'];
						}
						else if($arrAttributes[$iRowAtt]['name']=='Purity')
						{
							$strPurity = $arrAttributes[$iRowAtt]['option'];
						}
						else if($arrAttributes[$iRowAtt]['name']=='Color')
						{
							$strColor = $arrAttributes[$iRowAtt]['option'];
						}
					}
					   
					if(count($dtTmp1)>0)
					{
						$pro_update_status = 'UC';
						
						$str = "
						SELECT * 
						FROM `product` 
						WHERE `pro_sku` = '".$arrProduct[$iRow]['sku']."'
						and `pro_total_price` = '".$arrProduct[$iRow]['sale_price']."'
						and `pro_total_price` = '".$arrProduct[$iRow]['regular_price']."'
						and `pro_name` = '".$pro_name."'
						and `pro_wc_id` = '".$arrProduct[$iRow]['id']."'
						and `pro_status` ='".$arrProduct[$iRow]['status']."'";
							 
						$dtDataTable = getDatatable($str);
						
						if(count($dtDataTable)==0)
						{
							$pro_update_status = 'APIC';
						}
						
						
						
						//echo "update=";
						$strSql="
						UPDATE  `product` SET 
								`pro_wc_id`=".$arrProduct[$iRow]['id'].",
								`pro_name`='".$pro_name."',
								`pro_change_by`=1,
								`pro_change_on`=addtime(utc_timestamp(),'05:30:00'),
								`pro_permalink`='".$arrProduct[$iRow]['permalink']."',
								`pro_regular_price`='".$arrProduct[$iRow]['regular_price']."',
								`pro_sale_price`='".$arrProduct[$iRow]['sale_price']."',
								`pro_status`='".$arrProduct[$iRow]['status']."',
								`pro_color`='".$strColor."',
								`pro_purity`='".$strPurity."',
								`pro_size`='".$strRingSize."',
								`pro_weight`='".$arrProduct[$iRow]['weight']."',
								`pro_update_status`='".$pro_update_status."'
						 WHERE  `pro_sku`='".$arrProduct[$iRow]['sku']."'
						";
						//echo $strSql."<br>";
						execute_query($strSql);
					}
					else
					{
						$pro_update_status = 'APIC';
						
						//echo "insert=";
						$strSql="
						INSERT INTO `product`
									 (  `prom_id`,        `pro_wc_id`, 				   `pro_name`, `pro_diamond_price`, `pro_gold_price`, `pro_making_charge`, `pro_total_price`, `pro_change_by`, 
											`pro_change_on`, 					    `pro_permalink`, 					  `pro_sku`, 					 `pro_regular_price`, 
												  `pro_sale_price`, 					`pro_status`, 					   `pro_color`,    `pro_purity`,    `pro_size`,         `pro_weight`,
														`pro_update_status`) 
							 VALUES  (".$prom_id.",     ".$arrProduct[$iRow]['id'].",'".$pro_name."',0,					 0,				   0,					0,				  1,
											 addtime(utc_timestamp(),'05:30:00'),'".$arrProduct[$iRow]['permalink']."','".$arrProduct[$iRow]['sku']."',".$arrProduct[$iRow]['regular_price'].",
												".$arrProduct[$iRow]['sale_price'].",'".$arrProduct[$iRow]['status']."','".$strColor."','".$strPurity."','".$strRingSize."', '".$arrProduct[$iRow]['weight']."',
													 '".$pro_update_status."')
						";
						// echo $strSql;
						 execute_query($strSql);
					}
				
			   }
			   
			   
			echo '1';
			   
		}
		
		
	

?>